### ISSUE TITLE
Can't create queues, the app can't see if i'm on a profile page or not

### ISSUE THREAD

**Issue by Turtlecute33** [devRogi/GrowBotPremium#5]
I'm using the last release 2.3.1 and i tested it on chrome beta and Brave.
Seems that the app cant create a queue because it doesen't see that i'm on a profile page.
If i open the extension manager i can see this error:
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

**Comment by devRogi** [comment]
I’ve tested the latest release 2.3.1 on different accounts using both Chrome Beta and Brave, and I didn’t encounter any issues. The app was able to create a queue and recognize the profile page without any problems. It seems like the issue you’re experiencing might be related to the installation process or a server-side problem. You might want to try reinstalling the app.

**Comment by Turtlecute33** [comment]
Ok, i found that seems that only my account is limited from growbot, with other accounts it works on my pc, is there any way to unban me from growbot? :D

**Comment by devRogi** [comment]
It looks like the issue is specific to your account. To try and fix it, you'll need to clear your browsing data: history (ctrl+h), clear browsing data, advanced, time range (all time). Make sure to select everything, or you can try to select only the "Hosted Application Data" (Web Store) box, but it's better to delete everything, as this will automatically log you out of your Instagram account. After that, remove the Growbot extension from Chrome and restart your PC. After doing this, wait at least a day before trying to use Growbot again on your "banned" account.
